name: hifini-sign
on:
  schedule:
    - cron: 11 22 * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
      - name: Run sign
        run: |
          python3 ./main.py
        env:
          COOKIE1: ${{ secrets.COOKIE1 }}
          COOKIE2: ${{ secrets.COOKIE2 }}
          COOKIE3: ${{ secrets.COOKIE3 }}
          BARK_DEVICEKEY: ${{ secrets.BARK_DEVICEKEY }}
          BARK_ICON: ${{ secrets.BARK_ICON }}
